# UNTESTED TEMPLATE
# Add these criteria to your Sway config and tune for your setup.

for_window [app_id="taskbar-month-calendar"] floating enable, resize set 420 280, move position 1490 50
for_window [app_id="taskbar-year-calendar"] floating enable, resize set 980 760, move position 930 50
